// src/views/AboutTherapy.vue
<template>
  <div>
    <h4>Psychoterapia - dlaczego warto korzystać z psychoterapii?</h4>
    <b-card-group deck class="cards-top-margin">
      <b-card align="left">
        <p>
          Psychoterapia kierowana jest do osób dorosłych, młodzieży, dzieci i
          rodziców borykających się z problemami wychowawczymi, oraz do rodzin,
          małżeństw i par przeżywających problemy takie jak:
        </p>
        <ul>
          <li>
            uzależnienia typu; alkohol, narkotyki, hazard, leki, gry
            komputerowe,
          </li>
          <li>
            alkoholizm i inne uzależnienia w rodzinie, współmałżonka czy
            dziecka,
          </li>
          <li>zaburzenia emocjonalne: lęki i fobie, depresje, nerwice, natręctwa,</li>
          <li>brak samokontroli,</li>
          <li>zaburzenia odżywiania,</li>
          <li>trudności wychowawcze, problemy w kontaktach z dziećmi,</li>
          <li>trudności adaptacyjne, w nawiązaniu relacji,</li>
          <li>konflikty pokoleniowe w rodzinie,</li>
          <li>ciąża, poród i lęki z tym z wiązane,</li>
          <li>agresja, przemoc w rodzinie,</li>
          <li>choroba dziecka,</li>
          <li>żałoba po stracie dziecka, czy bliskiej osoby z rodziny,</li>
          <li>separacja, rozwód, rozstanie z bliską osobą,</li>
          <li>stres i frustracja,</li>
          <li>zaburzenia osobowości.</li>
        </ul>
        <p>Proponowane formy terapii to:</p>
        <ul>
          <li>Terapia Indywidualna</li>
          <li>Terapia Grupowa,</li>
          <li>Terapia Rodzinna,</li>
          <li>Terapia Małżeńska.</li>
        </ul>
        <p>Nie uciekaj od problemów, rozwiąż je z pomocą specjalisty!</p>
      </b-card>
      <b-card class="description">
        <p>
          Podjęcie pierwszego kroku w kierunku uzyskania pomocy, jest często
          najtrudniejsze, jednak samotne radzenie sobie z problemami, nawet
          jeżeli wydają się błahe, może być trudne a niekiedy wręcz niemożliwe
          do udźwignięcia.
        </p>
        <p>
          W trakcie spotkań, pacjent wraz z terapeutą, szuka przyczyn objawów,
          szuka możliwych rozwiązań, a tym samym daje sobie szansę na zmianę
          dotychczasowego funkcjonowania i myślenia o sobie, stwarza możliwość
          świadomego kierowania swoim życiem w przyszłości.
        </p>
        <p>
          Decydując się na terapię w gabinecie, pacjent ma zapewnioną konsultację,
          fachową pomoc w bezpiecznym, poufnym i życzliwym środowisku. Moja praca
          w procesie terapii polega przede wszystkim, na zapewnieniu wsparcia w
          rozwiązaniu problemu pacjenta, bez dokonywania oceny zaistniałej
          sytuacji. Szukam innych perspektyw w spojrzeniu na jego problem, badam
          różnorodne kierunki prowadzące do rozwiązania.
        </p>
        <p>
          Pierwsze spotkanie ma charakter konsultacyjny w trakcie którego
          pacjent i psychoterapeuta, decydują czy podjąć dalszą
          psychoterapię.
        </p>
      </b-card>
    </b-card-group>
  </div>
</template>

// src/views/AboutTherapy.tsx
import React from 'react';
import { CardGroup, Card } from 'react-bootstrap';

const AboutTherapy: React.FC = () => {
  return (
    <div>
      <h4>Psychoterapia - dlaczego warto korzystać z psychoterapii?</h4>
      <CardGroup className="cards-top-margin">
        <Card>
          <Card.Body className="text-left">
            <p>
              Psychoterapia kierowana jest do osób dorosłych, młodzieży, dzieci i
              rodziców borykających się z problemami wychowawczymi, oraz do rodzin,
              małżeństw i par przeżywających problemy takie jak:
            </p>
            <ul>
              <li>
                uzależnienia typu; alkohol, narkotyki, hazard, leki, gry
                komputerowe,
              </li>
              <li>
                alkoholizm i inne uzależnienia w rodzinie, współmałżonka czy
                dziecka,
              </li>
              <li>zaburzenia emocjonalne: lęki i fobie, depresje, nerwice, natręctwa,</li>
              <li>brak samokontroli,</li>
              <li>zaburzenia odżywiania,</li>
              <li>trudności wychowawcze, problemy w kontaktach z dziećmi,</li>
              <li>trudności adaptacyjne, w nawiązaniu relacji,</li>
              <li>konflikty pokoleniowe w rodzinie,</li>
              <li>ciąża, poród i lęki z tym z wiązane,</li>
              <li>agresja, przemoc w rodzinie,</li>
              <li>choroba dziecka,</li>
              <li>żałoba po stracie dziecka, czy bliskiej osoby z rodziny,</li>
              <li>separacja, rozwód, rozstanie z bliską osobą,</li>
              <li>stres i frustracja,</li>
              <li>zaburzenia osobowości.</li>
            </ul>
            <p>Proponowane formy terapii to:</p>
            <ul>
              <li>Terapia Indywidualna</li>
              <li>Terapia Grupowa,</li>
              <li>Terapia Rodzinna,</li>
              <li>Terapia Małżeńska.</li>
            </ul>
            <p>Nie uciekaj od problemów, rozwiąż je z pomocą specjalisty!</p>
          </Card.Body>
        </Card>
        <Card className="description">
          <Card.Body>
            <p>
              Podjęcie pierwszego kroku w kierunku uzyskania pomocy, jest często
              najtrudniejsze, jednak samotne radzenie sobie z problemami, nawet
              jeżeli wydają się błahe, może być trudne a niekiedy wręcz niemożliwe
              do udźwignięcia.
            </p>
            <p>
              W trakcie spotkań, pacjent wraz z terapeutą, szuka przyczyn objawów,
              szuka możliwych rozwiązań, a tym samym daje sobie szansę na zmianę
              dotychczasowego funkcjonowania i myślenia o sobie, stwarza możliwość
              świadomego kierowania swoim życiem w przyszłości.
            </p>
            <p>
              Decydując się na terapię w gabinecie, pacjent ma zapewnioną konsultację,
              fachową pomoc w bezpiecznym, poufnym i życzliwym środowisku. Moja praca
              w procesie terapii polega przede wszystkim, na zapewnieniu wsparcia w
              rozwiązaniu problemu pacjenta, bez dokonywania oceny zaistniałej
              sytuacji. Szukam innych perspektyw w spojrzeniu na jego problem, badam
              różnorodne kierunki prowadzące do rozwiązania.
            </p>
            <p>
              Pierwsze spotkanie ma charakter konsultacyjny w trakcie którego
              pacjent i psychoterapeuta, decydują czy podjąć dalszą
              psychoterapię.
            </p>
          </Card.Body>
        </Card>
      </CardGroup>
    </div>
  );
};

export default AboutTherapy;
